### ISSUE TITLE
More helpful feedback when profile configuration in magellan.json fails

### ISSUE THREAD

**Issue by qacwnfq** [TestArmada/magellan-saucelabs-executor#2]
Right now when specifying a browser and OS combination which doesn't exist the executor prints:

```
[ERROR] [Magellan] Executor sauce cannot resolve profile [object Object]
```

If the profile is print, it is a lot easier to fix this error in the test configs!

**Comment by archlichking** [comment]
@qacwnfq thanks for the feed back, this is fixed in v1.0.1, which is released yesterday.
